### ISSUE TITLE
Clone tags

### ISSUE THREAD

**Issue by s849** [morris-lab/PreviousCloneHunter#1]
Hello,

I was wondering how do you introduce tag information? Are individual clone tags incorporated into the reference genome and detected by mapping?

**Comment by sam-morris** [comment]
Hi - we only include the CellTag UTR in the reference genome. We include this information in the methods section of the paper. To extract CellTags we pull them from the bam files, using the surrounding CellTag UTR sequence as outlined in the CloneHunter pipeline. After clone-calling, we add this information as metadata for each cell.
