### ISSUE TITLE
CellTagMatrixCount

### ISSUE THREAD

**Issue by ylcheng** [morris-lab/PreviousCloneHunter#2]
I'm currently going though the tutorial for clonehunter and the following error occurs when I execute CellTagMatrixCount.
ct.mtx <- CellTagMatrixCount("./hf1.d15.barcodes.tsv.txt", "./hf1.d15.possorted.celltag.tsv")
Error in file(file, if (append) "a" else "w") : 
  invalid 'description' argument

Yim

**Comment by babiddy** [comment]
Hi Yim,

Thanks for opening an issue. I am not exactly sure what is causing this problem, but we think it might be the filename "hf1.d15.barcodes.tsv.txt". If you could try executing the command again but this time with the file name "hf1.d15.barcodes.tsv". I parsed the input file names lazily and I think the extra ".txt" extension on the filename may be causing the issue. If you could rename the barcodes file and remove the extra file extension then execute the command again we can tell if this is the case. Please let us know if this works and we can begin fixing the function.

Best,
Brent

**Comment by ylcheng** [comment]
Actually I have tried that and the same error occurred. At the end I opened Rscript and I executed the code in the CellTagMatrixCount function line by line and it is during this step (sink(summaryOut)) that the error popped up. Since the output of the summaryOut is not necessary, I was able to generate matrixOut file and continue with the tutorial. 

Yim

**Comment by babiddy** [comment]
Thank you for the response! I am glad you were able to work around this problem. It helps to know that the error occurred when writing the output file. If you have any other issues with the analysis, please let us know. 

Best,
Brent
